### ISSUE TITLE
RecordException 

### ISSUE THREAD

**Issue by millmill12345** [Synthesis-Collective/EnemyReleveler#2]
below exception occured

RecordException Wyrmstooth.esp => 0603D7:Wyrmstooth.esp: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
   at EnemyReleveler.Program.RunPatch(IPatcherState`2 state) in D:\_usr_files\_temp\Synthesis\9390d790-fde9-4896-804c-5465e5722955\Git\9bb794d5-52b0-4d1b-8265-3c99aa0ae6b4\Runner\EnemyReleveler\Program.cs:line 77
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 87
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 446
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 395
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 370
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel)
   at Synthesis.Bethesda.Execution.Runner.Run[TKey](String workingDirectory, ModPath outputPath, String dataFolder, IEnumerable`1 loadOrder, GameRelease release, IEnumerable`1 patchers, IRunReporter`1 reporter, CancellationToken cancellation, ModPath sourcePath, PersistenceMode persistenceMode, String persistencePath)

**Comment by theSkyseS** [comment]
Hello, @millmill12345, can you, please, find a record with id xx0603d7, where xx is Wyrmstooth index in your load order, and screenshot it here. Especially a "Factions" part?

**Comment by millmill12345** [comment]
Hi theSkyseS, thanks to respond. I searched it in xEdit, but that FormID wasn't found. It may have been issue by tring to refer unexist FormID...

**Comment by Noggog** [comment]
Handled with the #3 PR?

**Comment by Noggog** [comment]
I think this was handled.  Reopen if it recurs
